### ISSUE TITLE
Crash when spawning a specific unidentified villager

### ISSUE THREAD

**Issue by Foreck1** [crazysnailboy/VillagerTrades#32]
Hi, I'm a Dev of Rebirth of the Night.
I added a new villager but there's some other conflict causing crashes when generating villages or using a villager spawning egg. The crash itself is:

```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bound must be positive
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.getRandomCareer(VillagerRegistry.java:234)
    at net.minecraft.entity.passive.EntityVillager.populateBuyingList(EntityVillager.java:665)
    at net.minecraft.entity.passive.EntityVillager.finalizeMobSpawn(EntityVillager.java:862)
    at net.minecraft.entity.passive.EntityVillager.onInitialSpawn(EntityVillager.java:849)
    at net.minecraft.item.ItemMonsterPlacer.spawnCreature(ItemMonsterPlacer.java:238)
    at net.minecraft.item.ItemMonsterPlacer.onItemUse(ItemMonsterPlacer.java:95)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889)
    at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:481)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more
```

- Default mod villagers and trades are disabled in cfg file
- The custom villager **does** work without issues
- The mod "Village Names" is installed and used to dynamically generate skins for the new villager
Here are both the files for the new profession/career and its trades

I know this mod hasn't received an update in **3 years**, but I really hope that maybe this is an easy fix on my end.
[Shady Villager.zip](https://github.com/crazysnailboy/VillagerTrades/files/4447360/Shady.Villager.zip)

**Comment by Foreck1** [comment]
Managed to fix this, it was caused by various mods clashing together, I still hope this mod comes back to life.
